name = "NanotubesCAPs"
uuid = "7522fbb1-d567-4f2a-ae26-ee70159dd3d3"
version = "0.1.0"
authors = ["Miguel Ayala <miguel.guadarramaayala@mail.mcgill.ca>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RadiiPolynomial = "f2081a94-c849-46b6-8dc9-07bb90ed72a9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CairoMakie = "0.15.1"
Distances = "0.10.12"
ForwardDiff = "1.0.1"
IntervalArithmetic = "0.22.36"
JLD2 = "0.5.15"
LaTeXStrings = "1.4.0"
LineSearches = "7.4.0"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
Parameters = "0.12.3"
Printf = "1.11.0"
RadiiPolynomial = "0.8.24"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
UnPack = "1.0.2"
